name: pomodoro
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.0
  back_button_interceptor: ^8.0.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  awesome_notifications: ^0.10.0

dev_dependencies:
  build_runner: ^2.0.0
  hive_generator: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
 
  fonts:
    - family: PatuaOne
      fonts:
        - asset: assets/fonts/PatuaOne-Regular.ttf
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-SemiBold.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
    - family: DMMono
      fonts:
        - asset: assets/fonts/DMMono-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_SemiBold.ttf
